// To parse this JSON:
//
//   NSError *error;
//   IPShiftResponse *shiftResponse = [IPShiftResponse fromJSON:json encoding:NSUTF8Encoding error:&error];


// AUTOGENERATED by https://app.quicktype.io
#import <Foundation/Foundation.h>

@class IPShiftResponse;
@class IPShift;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Object interfaces

@interface IPShiftResponse : NSObject
@property (nonatomic, nullable, copy) NSArray<IPShift *> *shifts;

+ (_Nullable instancetype)fromJSON:(NSString *)json encoding:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
+ (_Nullable instancetype)fromData:(NSData *)data error:(NSError *_Nullable *)error;
- (NSString *_Nullable)toJSON:(NSStringEncoding)encoding error:(NSError *_Nullable *)error;
- (NSData *_Nullable)toData:(NSError *_Nullable *)error;
@end

@interface IPShift : NSObject
@property (nonatomic, nullable, copy) NSString *role;
@property (nonatomic, nullable, copy) NSString *name;
@property (nonatomic, nullable, copy) NSString *startDate;
@property (nonatomic, nullable, copy) NSString *endDate;
@property (nonatomic, nullable, copy) NSString *color;
@end

NS_ASSUME_NONNULL_END
